# Generated by Django 4.2 on 2023-05-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbase",
            options={"verbose_name": "Accounts", "verbose_name_plural": "Accounts"},
        ),
    ]
